- name: Arch Linux laptop setup
  hosts: localhost

  roles:
    - base
    - shell
#    - zsh
    - kde
    - power
    - systemd-boot
    - rclone
    - ssh
    - keepassxc
#    - audio
#    - fonts
#    - dotfiles
